### ISSUE TITLE
[test fail ] Store owner able to withdraw funds + Shopper is able to purchase a product

### ISSUE THREAD

**Issue by robbiekruszynski** [spacelover1/consensys-fp#2]
Hello, 
Going over your project now and noticed two tests not passing. 
Wondering if they are passing on your local? 

```
Contract: MarketPlace
       **Store Owner functionality
         Store owner able to withdraw funds:
     Error: Returned error: VM Exception while processing transaction: invalid opcode
      at Context.<anonymous> (test/market_place.test.js:145:54)
      at processTicksAndRejections (internal/process/task_queues.js:89:5)

Contract: MarketPlace
       Shopper  functionality
         Shopper is able to purchase a product:
     Error: Returned error: VM Exception while processing transaction: invalid opcode
      at Context.<anonymous> (test/market_place.test.js:181:54)
      at processTicksAndRejections (internal/process/task_queues.js:89:5)

```

**Comment by spacelover1** [comment]
Hello Robbie,
Yes, all tests are passing on my local machine, I can send a screenshots of
log, if it's needed.

**Comment by spacelover1** [comment]
[image: image.png]

Here's a screenshot of result of `truffle test` command, didnt have access
to my system at that time.
